name: Rust

on:
  push:
    branches: [ "axum" ]
  pull_request:
    branches: [ "axum" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Rust setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
